In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_csv("flats.csv")

In [5]:
df.head()

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3017 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3017 non-null   object
 1   link             3017 non-null   object
 2   society          3016 non-null   object
 3   price            3007 non-null   object
 4   area             3004 non-null   object
 5   areaWithType     3008 non-null   object
 6   bedRoom          3008 non-null   object
 7   bathroom         3008 non-null   object
 8   balcony          3008 non-null   object
 9   additionalRoom   1694 non-null   object
 10  address          3002 non-null   object
 11  floorNum         3006 non-null   object
 12  facing           2127 non-null   object
 13  agePossession    3007 non-null   object
 14  nearbyLocations  2913 non-null   object
 15  description      3008 non-null   object
 16  furnishDetails   2203 non-null   object
 17  features         2594 non-null   object
 18  rating           2676 non-null   object
 19  property_id      3008 non-null   object
dtypes: object(20)
memory usage: 471.5+ KB

In [7]:
df.duplicated().sum()

0

In [8]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                10
area                 13
areaWithType          9
bedRoom               9
bathroom              9
balcony               9
additionalRoom     1323
address              15
floorNum             11
facing              890
agePossession        10
nearbyLocations     104
description           9
furnishDetails      814
features            423
rating              341
property_id           9
dtype: int64

In [9]:
df.drop(columns=['link','property_id'], inplace=True)

In [10]:
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [11]:
df['society'].value_counts()

SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Orchard                                  32
Smart World Gems                                     32
Paras Dews                                           31
DLF The Ultima4.0 ★                                  31
DLF Regal Gardens3.9 ★                               30
M3M Woodshire4.0 ★                                   29
Shree Vardhman Flora3.8 ★                            29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         28
Godrej Nature Plus                                   27
Emaar Gurgaon Greens4.1 ★                            25
BPTP Terra3.8 ★                                      25
Vatika Gurgaon 213.7 ★                               24
Experion The Heartsong3.9 ★                          24
DLF New Town Heights 13.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Bestech Park View Residency3.9 ★                     23
Tata Primanti4.1 ★                                   22
Emaar Palm Gardens4.1 ★                              22
M3M Heights                                          22
ATS Triumph3.9 ★                                     22
Sare Crescent Parc3.5 ★                              21
ROF Ananda                                           21
Experion Windchants3.8 ★                             20
Godrej 1014.0 ★                                      20
Antriksh Heights3.7 ★                                19
Sare Homes                                           19
Mapsko Mount Ville4.1 ★                              18
ATS Tourmaline3.9 ★                                  18
Indiabulls Centrum Park3.7 ★                         18
Supertech Araville                                   18
Ambience Creacions                                   18
CHD Avenue 713.6 ★                                   18
Sobha City                                           18
Conscient Heritage Max4.3 ★                          17
GLS Arawali Homes3.8 ★                               17
M3M Golfestate4.4 ★                                  17
M3M Skywalk                                          17
Godrej Summit3.7 ★                                   17
Pareena Coban Residences                             17
M3M Merlin3.7 ★                                      16
Bestech Park View Grand Spa4.3 ★                     16
HCBS Sports Ville3.6 ★                               16
Godrej Oasis3.9 ★                                    15
Ansal Heights 86                                     15
Emaar MGF The Palm Drive4.1 ★                        15
Umang Monsoon Breeze                                 15
Vatika The Seven Lamps3.8 ★                          14
The Close North4.0 ★                                 14
MVN Athens3.7 ★                                      14
Indiabulls Enigma                                    14
Ireo Victory Valley4.1 ★                             14
Corona Optus3.9 ★                                    14
Orchid Petals4.1 ★                                   14
Ramsons Kshitij3.7 ★                                 14
Ireo Skyon4.0 ★                                      14
Imperia The Esfera                                   14
DLF The Primus3.9 ★                                  14
Umang Winter Hills3.9 ★                              14
Central Park Flower Valley                           13
Bestech Park View Ananda4.2 ★                        13
Puri Emerald Bay3.7 ★                                13
Ireo The Corridors                                   13
Alpha Corp GurgaonOne 844.0 ★                        11
SBTL Caladium                                        11
TARC Maceo3.8 ★                                      11
Raheja Vedaanta3.6 ★                                 11
Breez Global Hill View                               11
M3M Soulitude                                        11
DLF The Skycourt4.2 ★                                11
Adani M2K Oyster Grande3.9 ★                         11
Godrej Aria3.8 ★                                     11
Pyramid Urban Homes 2                                10
Pivotal Devaan                                       10
Zara Aavaas                                          10
Signature Global Synera3.4 ★                         10
Ramprastha The Edge Towers3.5 ★                      10
Godrej Air                                           10
DLF New Town Heights 24.0 ★                          10
ATS Kocoon                                           10
Emaar MGF Palm Hills4.0 ★                            10
Breez Global Heights4.2 ★                            10
Puri Diplomatic Greens4.0 ★                          10
Capital Residences 360                               10
Parsvnath Green Ville3.9 ★                            9
Bestech Park View Sanskruti4.2 ★                      9
ILD Greens4.1 ★                                       9
Pareena Mi Casa                                       9
Microtek Greenburg3.8 ★                               9
Vatika City4.1 ★                                      9
AIPL The Peaceful Homes3.9 ★                          9
ss                                                    8
GLS Avenue 51                                         8
Assotech Blith                                        8
M3M Capital                                           8
Birla Navya                                           8
AVL 36 Gurgaon3.7 ★                                   8
Orris Aster Court Premier                             8
Emaar Digihomes                                       8
The Lions CGHS                                        8
Tulip Ivory3.5 ★                                      8
Bestech Altura                                        8
M3M Skycity                                           8
Vatika Lifestyle Homes3.8 ★                           8
Emaar Imperial Gardens3.8 ★                           7
Ireo The Grand Arch4.0 ★                              7
Orris Carnation Residency3.7 ★                        7
AIPL Zen Residences                                   7
Ansal Housing Highland Park                           7
Signature Global Orchard Avenue3.6 ★                  7
Vipul Lavanya3.9 ★                                    7
Sare Green ParC Phase 3                               7
Trisara Our Homes 3                                   7
Signature Andour Heights3.8 ★                         7
Signature Global City                                 7
Sare Crescent Parc Royal Greens Phase 1               7
Mapsko Casa Bella3.8 ★                                7
HSIIDC Sidco Aravali                                  6
Pioneer Araya3.8 ★                                    6
Bestech Park View City4.1 ★                           6
Kiran Residency                                       6
BPTP Astaire Gardens3.7 ★                             6
Sidhartha NCR One Phase 14.2 ★                        6
Signature Global Park 4                               6
Suncity Vatsal Valley                                 6
Supertech Hues                                        6
M3M Sierra 68                                         6
Signature The Roselia3.6 ★                            6
Ashiana Mulberry                                      6
Mapsko Royale Ville3.7 ★                              6
Bestech Park View Spa Next4.0 ★                       6
DLF Regency Park 13.6 ★                               6
Signature Global City 63A                             6
Pyramid Urban                                         6
Shapoorji Pallonji Joyville Gurugram                  6
Greenopolis                                           6
Hero Homes                                            6
Parsvnath Exotica3.7 ★                                6
M3M The Marina4.0 ★                                   5
Signature Global the Millennia                        5
DLF Regency Park 24.0 ★                               5
Godrej Habitat                                        5
Central Park Flower Valley Aqua Front Towers          5
Tulip Monsella                                        5
Signature Global City 92                              5
Pioneer Park3.8 ★                                     5
Satya The Hermitage3.5 ★                              5
Silverglades The Melia                                5
Essel Towers                                          5
Vatika Sovereign Park                                 5
Krisumi Waterfall Residences                          5
Signature Global Grand IVA3.9 ★                       5
ATS Marigold                                          5
Ireo Uptown4.1 ★                                      5
Pareena Laxmi Apartments3.6 ★                         5
Emaar MGF Emerald Estate3.8 ★                         5
Signature Global City 81                              5
DLF Park Place4.1 ★                                   5
Vatika City Homes3.9 ★                                5
Central Park Resorts4.4 ★                             5
Conscient Elevate                                     5
Apna Enclave                                          5
Green Court3.7 ★                                      5
Adani Brahma Samsara Vilasa                           5
Ashiana Anmol3.5 ★                                    5
Signature Global City 37D Ph 2                        5
Signature The Serenas                                 4
Tata Gurgaon Gateway3.8 ★                             4
Godrej Icon                                           4
Unitech Vistas                                        4
Orris Aster Court                                     4
ILD Grand                                             4
Railway Officers RPF Society                          4
Raheja Navodaya3.6 ★                                  4
Global Hill View                                      4
Corona Gracieux                                       4
Krrish Provence Estate                                4
DLF The Skycourt                                      4
SS The Coralwood3.4 ★                                 4
Prime Habitat                                         4
Lotus Homz4.0 ★                                       4
Ramprastha Primera                                    4
Sare Petioles                                         4
Unitech Fresco3.8 ★                                   4
Emaar Palm Heights                                    4
Ramprastha Skyz                                       4
Godrej Frontier3.7 ★                                  4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
DLF New Town Heights3.7 ★                             4
Tulip Purple                                          3
Shree Arihant Apartment                               3
Mahindra Aura4.2 ★                                    3
Paras Quartier                                        3
ATS Kocoon4.2 ★                                       3
Puri Diplomatic Greens3.9 ★                           3
Unitech Heritage City                                 3
Shri Banke Bihari Society3.8 ★                        3
AIPL Club Residences                                  3
Ambience Lagoon3.9 ★                                  3
Vatika Independent Floors3.8 ★                        3
Raheja Atharva3.6 ★                                   3
Dhoot Time Residency4.0 ★                             3
DLF Royalton Tower                                    3
Sunischit Apartments                                  3
Unitech Uniworld Gardens3.8 ★                         3
Guru Gram Haryana CGHS4.1 ★                           3
DLF Belvedere Towers3.8 ★                             3
Unitech Sunbreeze                                     3
Krrish Florence Estate                                3
Adani Aangan Arcade                                   3
Sare Green Parc                                       3
Chintels Paradiso3.9 ★                                3
Essel Tower                                           3
The Roselia 2                                         3
Maxworth City Residences                              3
Deepak Minda                                          3
Kendriya Vihar4.1 ★                                   3
Unitech The Residences3.7 ★                           3
Sidhartha NCR One                                     3
DLF The Arbour                                        3
Whiteland Blissville                                  3
Valley View Estate                                    3
Signature Global Solera 2                             3
Raheja Sampada                                        3
Sidhartha NCR Greens4.3 ★                             3
Pivotal Riddhi Siddhi                                 3
Bestech Park View City 23.9 ★                         3
My Home                                               3
AFNHB Jalvayu Vihar3.7 ★                              3
Brisk Lumbini Terrace Homes                           3
Piedmont Taksila heights3.6 ★                         3
Siddhartha Apartment                                  3
Smriti Apartment                                      3
Vatika Xpressions                                     3
DLF Carlton Estate4.0 ★                               3
SS Almeria                                            3
Sukhshanti Apartment                                  3
DLF The Grove                                         3
Spaze Privvy The Address3.9 ★                         3
Sapphire Eighty Three                                 3
Tulip White3.5 ★                                      3
Spaze Privy3.9 ★                                      3
Tulip Lemon3.9 ★                                      3
Shri Ram Apartments                                   3
Conscient Habitat3.6 ★                                3
Satya Element One                                     3
Pyramid Elite                                         3
Apex Our Homes                                        3
Suncity Platinum Towers                               3
Spaze Privy AT43.9 ★                                  3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Raheja Revanta                                        3
Tulip Petals3.6 ★                                     3
Godrej Nature Plus Serenity                           2
Tulip Orange3.9 ★                                     2
Supertech Hill Town                                   2
Housing Board Colony                                  2
NBCC Heights3.9 ★                                     2
Sahara Grace                                          2
Oriental Valley CHS                                   2
Suncity Avenue 76                                     2
Adani Aangan Galleria                                 2
HCBS Sports Ville                                     2
Aqua Front Towers                                     2
Ansal API Esencia3.7 ★                                2
DLF The Icon3.7 ★                                     2
Professors Enclave CGHS                               2
Paras Irene3.7 ★                                      2
Mittal Surya Vihar                                    2
Suposhaa Smartworld Orchard                           2
DLF The Belaire3.9 ★                                  2
Suncity Avenue 1023.9 ★                               2
BPTP Amstoria3.8 ★                                    2
Emaar MGF The Enclave                                 2
Vipul Belmonte3.9 ★                                   2
Bestech Park View Sanskruti4.1 ★                      2
BPTP Mansions Park Prime                              2
M3M Ikonic                                            2
The Penthouses at the Hibiscus                        2
SS Hibiscus                                           2
Viridian The Plaza 106                                2
Tulip Leaf                                            2
Tulip Violet                                          2
Vatika Emilia Floors3.7 ★                             2
Emaar MGF Palm Studios                                2
Orchid Island4.2 ★                                    2
Signature Global The Millennia 3                      2
Samaspurkunj                                          2
M3M Sky Lofts                                         2
ROF Aalayas3.8 ★                                      2
AWHO Shanti Vihar4.0 ★                                2
Residency Grand                                       2
Ganga Apartment                                       2
Raheja Atlantis3.8 ★                                  2
Ashiana Anmol                                         2
Central Park 2 Bellevue                               2
om appartments                                        2
Shapoorji Pallonji Joyville                           2
DLF The Crest3.6 ★                                    2
Today Callidora                                       2
Landmark The Residency                                2
Vasant Appartments                                    2
Maruti Vihar                                          2
Ambience Caitriona                                    2
Bhagwati Sadan                                        2
Unitech Uniworld Gardens 23.4 ★                       2
BPTP Pedestal                                         2
MRG World Ultimus                                     2
Sidhivinayak Apartments                               2
Mapsko Paradise3.9 ★                                  2
Park Royal Apartment                                  2
Ramprastha The Atrium3.4 ★                            2
Mahindra Luminare4.0 ★                                2
Suncity Heights3.7 ★                                  2
BPTP Freedom Park Life4.0 ★                           2
Jammu and Kashmir Bank Employees CGHS3.7 ★            2
Puri The Aravallis                                    2
Ansal Heights3.2 ★                                    2
Ramprastha City                                       2
M3M Urbana                                            2
Ardee City3.8 ★                                       2
Palam Vihar Society                                   2
Vatika INXT Floors                                    2
Raheja Vanya                                          2
Surendra Avenue 69                                    2
Supertech Hilltown                                    2
Tulsiani Easy in Homes                                2
Breeze Global Heights                                 2
CGHS Airport Apartment                                2
Vipul World Floors                                    2
Ansal API Celebrity Suites                            2
M3M Latitude                                          2
Apartment                                             2
Element One Service                                   2
Pioneer Urban Presidia                                2
Elan The Presidential                                 2
Bestech Spa Signature                                 2
Green Campus CHS                                      2
Lavanya Apartments                                    2
Milan CGHS 9                                          2
Silverglades Hightown Residences                      2
Dlf City                                              2
The Close South3.9 ★                                  2
lagoon apartment                                      2
Surbhi Apartment                                      1
The Center Court                                      1
Divya Apartments                                      1
Maple Heights                                         1
ikon tower baani city centre                          1

In [12]:
df['society'].value_counts().shape

(638,)

In [13]:
import re
text = df['society'][2935]
text

'Godrej Frontier3.7 ★'

In [14]:
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '',str(name)).strip()).str.lower()

In [15]:
df['society'].value_counts().head(10)

tulip violet                            75
ss the leaf                             74
shapoorji pallonji joyville gurugram    45
dlf new town heights                    38
signature global park                   36
shree vardhman victoria                 35
smart world orchard                     32
emaar mgf emerald floors premier        32
smart world gems                        32
paras dews                              31
Name: society, dtype: int64

In [16]:
df['price'].value_counts()

1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.5 Crore           59
1.2 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
1.45 Crore          31
85 Lac              31
1.05 Crore          30
2.5 Crore           29
60 Lac              29
40 Lac              29
2.1 Crore           26
45 Lac              26
65 Lac              25
35 Lac              23
2.35 Crore          23
1.85 Crore          23
3 Crore             22
70 Lac              21
55 Lac              20
2.25 Crore          20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
2.6 Crore           15
1.38 Crore          15
2.45 Crore          14
3.4 Crore           14
2.15 Crore          14
1.32 Crore          13
3.25 Crore          13
78 Lac              13
92 Lac              13
82 Lac              13
38 Lac              13
2.7 Crore           13
1.95 Crore          12
1.42 Crore          12
5 Crore             12
42 Lac              12
2.8 Crore           12
88 Lac              11
32 Lac              11
25 Lac              11
1.08 Crore          11
Price on Request    11
28 Lac              10
1.28 Crore          10
87 Lac              10
26 Lac              10
1.78 Crore          10
1.12 Crore          10
2.55 Crore          10
1.68 Crore           9
3.45 Crore           9
36 Lac               9
22 Lac               9
2.05 Crore           9
4 Crore              9
1.72 Crore           9
99 Lac               9
2.85 Crore           9
27 Lac               8
1.76 Crore           8
98 Lac               8
1.18 Crore           8
1.26 Crore           8
1.54 Crore           8
4.25 Crore           8
2.75 Crore           8
3.2 Crore            8
6 Crore              8
48 Lac               8
6.5 Crore            8
20 Lac               8
56 Lac               8
86 Lac               8
1.36 Crore           7
1.27 Crore           7
97 Lac               7
3.7 Crore            7
1.19 Crore           7
3.3 Crore            7
72 Lac               7
2.9 Crore            7
1.29 Crore           7
46 Lac               7
39 Lac               7
1.02 Crore           7
1.99 Crore           7
79 Lac               7
1.59 Crore           6
43 Lac               6
1.49 Crore           6
1.01 Crore           6
2.95 Crore           6
3.9 Crore            6
96 Lac               6
3.65 Crore           6
5.5 Crore            6
1.07 Crore           6
1.98 Crore           6
21 Lac               6
54 Lac               6
1.39 Crore           6
3.35 Crore           6
1.13 Crore           6
71.5 Lac             6
37 Lac               6
4.1 Crore            6
1.34 Crore           6
3.05 Crore           6
1.14 Crore           6
1.16 Crore           6
1.51 Crore           6
1.24 Crore           5
1.33 Crore           5
1.17 Crore           5
2.22 Crore           5
6.75 Crore           5
1.91 Crore           5
1.82 Crore           5
2.78 Crore           5
1.69 Crore           5
1.44 Crore           5
49 Lac               5
3.75 Crore           5
1.92 Crore           5
1.43 Crore           5
66 Lac               5
2.29 Crore           5
1.79 Crore           5
93 Lac               5
1.62 Crore           5
1.83 Crore           5
1.93 Crore           5
4.5 Crore            5
64 Lac               5
2.12 Crore           5
29 Lac               5
24 Lac               5
1.47 Crore           5
68 Lac               5
1.64 Crore           4
2.09 Crore           4
1.37 Crore           4
5.25 Crore           4
3.6 Crore            4
4.3 Crore            4
5.6 Crore            4
1.22 Crore           4
58 Lac               4
4.85 Crore           4
62 Lac               4
1.23 Crore           4
1.77 Crore           4
41.5 Lac             4
1.52 Crore           4
28.5 Lac             4
1.73 Crore           4
33 Lac               4
7 Crore              4
1.31 Crore           4
36.5 Lac             4
1.48 Crore           4
5.9 Crore            4
3.95 Crore           4
6.15 Crore           4
73 Lac               4
1.58 Crore           4
1.71 Crore           4
89 Lac               4
67 Lac               4
31 Lac               4
1.66 Crore           4
74 Lac               4
3.1 Crore            4
2.24 Crore           3
83 Lac               3
72.5 Lac             3
47 Lac               3
2.36 Crore           3
1.21 Crore           3
1.04 Crore           3
4.75 Crore           3
2.03 Crore           3
3.8 Crore            3
64.5 Lac             3
91 Lac               3
5.8 Crore            3
4.8 Crore            3
1.67 Crore           3
2.51 Crore           3
3.49 Crore           3
2.01 Crore           3
2.08 Crore           3
51 Lac               3
52 Lac               3
84 Lac               3
69 Lac               3
1.57 Crore           3
1.41 Crore           3
3.15 Crore           3
2.79 Crore           3
3.85 Crore           3
2.28 Crore           3
34 Lac               3
1.63 Crore           3
94 Lac               3
1.09 Crore           3
4.2 Crore            3
1.88 Crore           3
2.33 Crore           3
2.23 Crore           2
1.46 Crore           2
77.5 Lac             2
53.5 Lac             2
4.49 Crore           2
2.58 Crore           2
6.2 Crore            2
8.5 Crore            2
2.14 Crore           2
27.1 Lac             2
53 Lac               2
2.52 Crore           2
8 Crore              2
2.41 Crore           2
2.57 Crore           2
56.2 Lac             2
3.55 Crore           2
1.87 Crore           2
3.32 Crore           2
3.21 Crore           2
4.6 Crore            2
4.26 Crore           2
2.13 Crore           2
2.02 Crore           2
5.2 Crore            2
14 Crore             2
2.87 Crore           2
2.99 Crore           2
2.26 Crore           2
1.56 Crore           2
5.7 Crore            2
52.56 Lac            2
87.5 Lac             2
71 Lac               2
3.29 Crore           2
59 Lac               2
2.91 Crore           2
31.5 Lac             2
41 Lac               2
98.5 Lac             2
2.17 Crore           2
25.5 Lac             2
4.55 Crore           2
7.5 Crore            2
27.75 Lac            2
4.45 Crore           2
4.7 Crore            2
2.04 Crore           2
11 Crore             2
88.5 Lac             2
54.8 Lac             1
63.4 Lac             1
82.5 Lac             1
3.78 Crore           1
2.06 Crore           1
2.07 Crore           1
3.98 Crore           1
7.4 Crore            1
4.02 Crore           1
2.64 Crore           1
44 Lac               1
37.1 Lac             1
97.5 Lac             1
2.38 Crore           1
2.49 Crore           1
97.04 Lac            1
98.88 Lac            1
2.32 Crore           1
4.21 Crore           1
4.16 Crore           1
15 Crore             1
4.52 Crore           1
89.77 Lac            1
73.53 Lac            1
26.5 Lac             1
26.9 Lac             1
1.84 Crore           1
8.44 Crore           1
68.85 Lac            1
39.5 Lac             1
13.2 Crore           1
2.92 Crore           1
61 Lac               1
64.45 Lac            1
2.69 Crore           1
3.99 Crore           1
2.96 Crore           1
57 Lac               1
95.5 Lac             1
37.5 Lac             1
96.07 Lac            1
94.5 Lac             1
29.8 Lac             1
19 Lac               1
88.4 Lac             1
6.02 Crore           1
32.5 Lac             1
7.9 Crore            1
70.85 Lac            1
3.23 Crore           1
40.3 Lac             1
3.72 Crore           1
94.99 Lac            1
1.86 Crore           1
2.54 Crore           1
9 Crore              1
7.52 Crore           1
85.75 Lac            1
87.99 Lac            1
86.99 Lac            1
9.95 Crore           1
9.2 Crore            1
86.92 Lac            1
49.5 Lac             1
16 Lac               1
2.44 Crore           1
2.86 Crore           1
1.97 Crore           1
1.53 Crore           1
7.8 Crore            1
4.4 Crore            1
1.74 Crore           1
2.72 Crore           1
5.31 Crore           1
3.19 Crore           1
4.63 Crore           1
2.98 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
5.3 Crore            1
2.21 Crore           1
2.63 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
95.75 Lac            1
3.46 Crore           1
5.4 Crore            1
55.6 Lac             1
4.95 Crore           1
54.99 Lac            1
2.82 Crore           1
7.15 Crore           1
6.25 Crore           1
29.99 Lac            1
23 Lac               1
31.75 Lac            1
3.87 Crore           1
29.5 Lac             1
3.67 Crore           1
8.25 Crore           1
2.37 Crore           1
4.67 Crore           1
3.39 Crore           1
3.63 Crore           1
2.34 Crore           1
3.79 Crore           1
5.49 Crore           1
6.3 Crore            1
11.25 Crore          1
98.1 Lac             1
55.5 Lac             1
9.3 Crore            1
2.77 Crore           1
2.11 Crore           1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
24.5 Lac             1
17.5 Lac             1
20.5 Lac             1
47.5 Lac             1
42.5 Lac             1
1.11 Crore           1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
90.5 Lac             1
52.5 Lac             1
2.62 Crore           1
4.86 Crore           1
5.15 Crore           1
1.06 Crore           1
26.1 Lac             1
81 Lac               1
8.35 Crore           1
6.44 Crore           1
7.56 Crore           1
4.79 Crore           1
2.97 Crore           1
94.25 Lac            1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
35.5 Lac             1
4.94 Crore           1
10.75 Crore          1
9.14 Crore           1
62.5 Lac             1
Name: price, dtype: int64

In [17]:
df[df['price'] == 'Price on Request']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
25,5 BHK Flat in Sector 1 Gurgaon,the new people apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN
1644,4 BHK Flat in Sector 50 Gurgaon,ss hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1972,1 BHK Flat in Sector 31 Gurgaon,raheja atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
2054,2 BHK Flat in Sector 79 Gurgaon,supertech araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
2357,2 BHK Flat in Sector 37D Gurgaon,the millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2522,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2549,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
2640,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2959,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
2972,4 BHK Flat in Gwal Pahari,krrish provence estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
2973,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [18]:
df = df[df['price'] != 'Price on Request']

In [19]:
df.shape

(3006, 18)

In [20]:
df['price'].value_counts()

1.25 Crore     79
1.1 Crore      61
1.4 Crore      60
1.2 Crore      59
1.5 Crore      59
90 Lac         58
1.3 Crore      57
95 Lac         53
2 Crore        51
1.75 Crore     47
1 Crore        46
1.6 Crore      43
1.35 Crore     41
1.9 Crore      40
1.55 Crore     40
75 Lac         38
1.65 Crore     38
1.7 Crore      37
1.8 Crore      37
80 Lac         36
2.2 Crore      34
1.15 Crore     33
50 Lac         33
1.45 Crore     31
85 Lac         31
1.05 Crore     30
2.5 Crore      29
40 Lac         29
60 Lac         29
2.1 Crore      26
45 Lac         26
65 Lac         25
1.85 Crore     23
35 Lac         23
2.35 Crore     23
3 Crore        22
70 Lac         21
2.25 Crore     20
55 Lac         20
3.5 Crore      19
2.4 Crore      18
2.3 Crore      18
30 Lac         17
2.65 Crore     16
1.38 Crore     15
2.6 Crore      15
2.15 Crore     14
3.4 Crore      14
2.45 Crore     14
2.7 Crore      13
92 Lac         13
78 Lac         13
3.25 Crore     13
82 Lac         13
1.32 Crore     13
38 Lac         13
1.42 Crore     12
42 Lac         12
5 Crore        12
2.8 Crore      12
1.95 Crore     12
88 Lac         11
1.08 Crore     11
32 Lac         11
25 Lac         11
26 Lac         10
1.12 Crore     10
28 Lac         10
87 Lac         10
1.28 Crore     10
1.78 Crore     10
2.55 Crore     10
99 Lac          9
1.68 Crore      9
36 Lac          9
22 Lac          9
2.05 Crore      9
2.85 Crore      9
4 Crore         9
3.45 Crore      9
1.72 Crore      9
3.2 Crore       8
4.25 Crore      8
20 Lac          8
6 Crore         8
86 Lac          8
1.76 Crore      8
98 Lac          8
48 Lac          8
6.5 Crore       8
1.26 Crore      8
1.54 Crore      8
27 Lac          8
1.18 Crore      8
56 Lac          8
2.75 Crore      8
39 Lac          7
72 Lac          7
1.36 Crore      7
1.27 Crore      7
1.29 Crore      7
3.7 Crore       7
46 Lac          7
3.3 Crore       7
97 Lac          7
79 Lac          7
1.02 Crore      7
2.9 Crore       7
1.99 Crore      7
1.19 Crore      7
37 Lac          6
1.07 Crore      6
5.5 Crore       6
1.13 Crore      6
3.65 Crore      6
1.59 Crore      6
1.98 Crore      6
3.9 Crore       6
1.39 Crore      6
1.14 Crore      6
2.95 Crore      6
1.49 Crore      6
96 Lac          6
43 Lac          6
21 Lac          6
3.35 Crore      6
1.34 Crore      6
71.5 Lac        6
1.01 Crore      6
4.1 Crore       6
1.16 Crore      6
54 Lac          6
3.05 Crore      6
1.51 Crore      6
1.92 Crore      5
1.17 Crore      5
1.69 Crore      5
6.75 Crore      5
2.22 Crore      5
1.43 Crore      5
1.82 Crore      5
2.78 Crore      5
3.75 Crore      5
1.33 Crore      5
1.91 Crore      5
1.24 Crore      5
1.44 Crore      5
49 Lac          5
66 Lac          5
2.29 Crore      5
1.79 Crore      5
93 Lac          5
1.62 Crore      5
1.83 Crore      5
1.93 Crore      5
4.5 Crore       5
64 Lac          5
2.12 Crore      5
29 Lac          5
24 Lac          5
1.47 Crore      5
68 Lac          5
1.64 Crore      4
2.09 Crore      4
1.37 Crore      4
5.25 Crore      4
3.6 Crore       4
4.3 Crore       4
5.6 Crore       4
1.22 Crore      4
58 Lac          4
4.85 Crore      4
62 Lac          4
1.23 Crore      4
1.77 Crore      4
41.5 Lac        4
1.52 Crore      4
28.5 Lac        4
1.73 Crore      4
33 Lac          4
7 Crore         4
1.31 Crore      4
36.5 Lac        4
1.48 Crore      4
5.9 Crore       4
3.95 Crore      4
6.15 Crore      4
73 Lac          4
1.58 Crore      4
1.71 Crore      4
89 Lac          4
67 Lac          4
31 Lac          4
1.66 Crore      4
74 Lac          4
3.1 Crore       4
2.24 Crore      3
83 Lac          3
72.5 Lac        3
47 Lac          3
2.36 Crore      3
1.21 Crore      3
1.04 Crore      3
4.75 Crore      3
2.03 Crore      3
3.8 Crore       3
64.5 Lac        3
91 Lac          3
5.8 Crore       3
4.8 Crore       3
1.67 Crore      3
2.51 Crore      3
3.49 Crore      3
2.01 Crore      3
2.08 Crore      3
51 Lac          3
52 Lac          3
84 Lac          3
69 Lac          3
1.57 Crore      3
1.41 Crore      3
3.15 Crore      3
2.79 Crore      3
3.85 Crore      3
2.28 Crore      3
34 Lac          3
1.63 Crore      3
94 Lac          3
1.09 Crore      3
4.2 Crore       3
1.88 Crore      3
2.33 Crore      3
2.23 Crore      2
1.46 Crore      2
77.5 Lac        2
53.5 Lac        2
4.49 Crore      2
2.58 Crore      2
6.2 Crore       2
8.5 Crore       2
2.14 Crore      2
27.1 Lac        2
53 Lac          2
2.52 Crore      2
8 Crore         2
4.26 Crore      2
2.57 Crore      2
56.2 Lac        2
3.55 Crore      2
1.87 Crore      2
3.32 Crore      2
3.21 Crore      2
4.6 Crore       2
2.13 Crore      2
2.41 Crore      2
2.02 Crore      2
5.2 Crore       2
14 Crore        2
2.87 Crore      2
2.99 Crore      2
2.26 Crore      2
1.56 Crore      2
5.7 Crore       2
52.56 Lac       2
87.5 Lac        2
71 Lac          2
3.29 Crore      2
59 Lac          2
2.91 Crore      2
31.5 Lac        2
41 Lac          2
98.5 Lac        2
2.17 Crore      2
25.5 Lac        2
4.55 Crore      2
7.5 Crore       2
27.75 Lac       2
4.45 Crore      2
4.7 Crore       2
2.04 Crore      2
11 Crore        2
88.5 Lac        2
54.8 Lac        1
63.4 Lac        1
82.5 Lac        1
3.78 Crore      1
2.06 Crore      1
2.07 Crore      1
3.98 Crore      1
7.4 Crore       1
4.02 Crore      1
2.64 Crore      1
44 Lac          1
37.1 Lac        1
97.5 Lac        1
2.38 Crore      1
2.49 Crore      1
97.04 Lac       1
98.88 Lac       1
2.32 Crore      1
4.21 Crore      1
4.16 Crore      1
15 Crore        1
4.52 Crore      1
89.77 Lac       1
73.53 Lac       1
26.5 Lac        1
26.9 Lac        1
1.84 Crore      1
8.44 Crore      1
68.85 Lac       1
39.5 Lac        1
13.2 Crore      1
2.92 Crore      1
61 Lac          1
64.45 Lac       1
2.69 Crore      1
3.99 Crore      1
2.96 Crore      1
57 Lac          1
95.5 Lac        1
37.5 Lac        1
96.07 Lac       1
94.5 Lac        1
29.8 Lac        1
19 Lac          1
88.4 Lac        1
6.02 Crore      1
32.5 Lac        1
7.9 Crore       1
70.85 Lac       1
3.23 Crore      1
40.3 Lac        1
3.72 Crore      1
94.99 Lac       1
1.86 Crore      1
2.54 Crore      1
9 Crore         1
7.52 Crore      1
85.75 Lac       1
87.99 Lac       1
86.99 Lac       1
9.95 Crore      1
9.2 Crore       1
86.92 Lac       1
49.5 Lac        1
16 Lac          1
2.44 Crore      1
2.86 Crore      1
1.97 Crore      1
1.53 Crore      1
7.8 Crore       1
4.63 Crore      1
1.74 Crore      1
2.72 Crore      1
5.31 Crore      1
3.19 Crore      1
4.4 Crore       1
2.98 Crore      1
66.99 Lac       1
4.78 Crore      1
6.16 Crore      1
5.3 Crore       1
2.21 Crore      1
2.63 Crore      1
89.5 Lac        1
2.48 Crore      1
99.5 Lac        1
3.83 Crore      1
95.75 Lac       1
3.46 Crore      1
5.4 Crore       1
55.6 Lac        1
4.95 Crore      1
54.99 Lac       1
2.82 Crore      1
7.15 Crore      1
6.25 Crore      1
29.99 Lac       1
23 Lac          1
31.75 Lac       1
3.87 Crore      1
29.5 Lac        1
3.67 Crore      1
8.25 Crore      1
2.37 Crore      1
4.67 Crore      1
3.39 Crore      1
3.63 Crore      1
2.34 Crore      1
3.79 Crore      1
5.49 Crore      1
6.3 Crore       1
11.25 Crore     1
98.1 Lac        1
55.5 Lac        1
9.3 Crore       1
2.77 Crore      1
2.11 Crore      1
6.1 Crore       1
5.75 Crore      1
10 Crore        1
24.5 Lac        1
17.5 Lac        1
20.5 Lac        1
47.5 Lac        1
42.5 Lac        1
1.11 Crore      1
2.61 Crore      1
65.5 Lac        1
53.2 Lac        1
90.5 Lac        1
52.5 Lac        1
2.62 Crore      1
4.86 Crore      1
5.15 Crore      1
1.06 Crore      1
26.1 Lac        1
81 Lac          1
8.35 Crore      1
6.44 Crore      1
7.56 Crore      1
4.79 Crore      1
2.97 Crore      1
94.25 Lac       1
80.5 Lac        1
93.75 Lac       1
85.5 Lac        1
68.5 Lac        1
79.9 Lac        1
71.2 Lac        1
27.5 Lac        1
23.5 Lac        1
35.5 Lac        1
4.94 Crore      1
10.75 Crore     1
9.14 Crore      1
62.5 Lac        1
Name: price, dtype: int64

In [21]:
def convert_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [22]:
df['price'] = df['price'].str.split(' ').apply(convert_price)

In [23]:
df['price'].value_counts()

1.25     79
1.10     61
0.90     60
1.40     60
1.50     59
1.20     59
1.30     57
0.95     55
2.00     51
1.75     47
1.00     46
1.60     43
1.35     41
1.55     40
1.90     40
1.65     38
0.75     38
0.80     37
1.70     37
1.80     37
2.20     34
0.50     33
1.15     33
0.85     32
0.40     31
1.45     31
1.05     30
0.60     29
2.50     29
0.65     28
2.10     26
0.45     26
0.35     24
1.85     23
2.35     23
0.55     22
3.00     22
0.70     21
2.25     20
0.30     19
3.50     19
2.30     18
2.40     18
0.28     17
2.65     16
0.78     15
0.88     15
1.38     15
2.60     15
0.32     14
2.45     14
0.82     14
3.40     14
0.38     14
2.15     14
0.26     13
0.36     13
0.92     13
1.32     13
3.25     13
0.42     13
2.70     13
5.00     12
0.27     12
1.95     12
2.80     12
1.42     12
0.87     12
0.56     12
0.25     11
0.98     11
1.08     11
0.99     11
1.28     10
1.12     10
2.55     10
0.72     10
0.71     10
1.78     10
2.85      9
1.68      9
0.97      9
0.86      9
1.72      9
0.20      9
4.00      9
3.45      9
2.05      9
0.22      9
3.20      8
0.48      8
6.00      8
2.75      8
4.25      8
1.18      8
1.54      8
0.54      8
1.26      8
0.96      8
6.50      8
1.76      8
0.37      7
2.90      7
1.29      7
0.39      7
0.79      7
3.70      7
1.27      7
1.36      7
0.46      7
3.30      7
1.19      7
1.99      7
1.02      7
1.07      6
0.29      6
5.50      6
3.90      6
3.65      6
0.43      6
1.59      6
1.98      6
0.41      6
0.89      6
0.49      6
2.95      6
0.94      6
1.16      6
1.13      6
0.21      6
1.34      6
1.51      6
1.01      6
1.39      6
4.10      6
0.66      6
3.05      6
1.14      6
0.53      6
0.24      6
0.64      6
1.49      6
3.35      6
6.75      5
3.75      5
0.68      5
1.92      5
1.47      5
1.62      5
1.33      5
0.33      5
0.69      5
4.50      5
0.62      5
1.93      5
0.93      5
1.69      5
1.91      5
1.83      5
1.79      5
0.74      5
1.44      5
2.29      5
1.82      5
2.22      5
1.17      5
0.67      5
1.43      5
2.12      5
2.78      5
1.24      5
1.77      4
1.73      4
7.00      4
4.85      4
5.25      4
1.37      4
3.10      4
4.30      4
1.66      4
1.22      4
1.58      4
1.31      4
1.52      4
0.31      4
1.48      4
2.09      4
0.47      4
0.91      4
5.60      4
5.90      4
0.58      4
1.23      4
6.15      4
1.71      4
3.60      4
1.64      4
3.95      4
0.73      4
1.21      3
3.85      3
1.88      3
2.24      3
1.41      3
2.79      3
2.33      3
4.75      3
0.83      3
4.20      3
1.57      3
0.51      3
2.36      3
0.52      3
3.15      3
0.34      3
1.09      3
3.49      3
2.01      3
0.84      3
5.80      3
2.28      3
3.80      3
2.03      3
2.08      3
1.67      3
1.63      3
1.04      3
4.80      3
2.51      3
2.52      2
8.00      2
6.20      2
2.17      2
2.13      2
14.00     2
2.23      2
4.49      2
4.26      2
2.14      2
2.02      2
2.41      2
1.46      2
0.81      2
8.50      2
3.21      2
2.26      2
2.57      2
1.87      2
4.70      2
4.45      2
2.87      2
2.99      2
3.32      2
1.56      2
2.04      2
3.29      2
4.55      2
0.59      2
5.20      2
2.91      2
0.23      2
7.50      2
11.00     2
5.70      2
4.60      2
2.58      2
3.55      2
2.07      1
0.44      1
3.67      1
2.32      1
1.86      1
3.46      1
2.06      1
0.63      1
9.20      1
2.49      1
2.64      1
2.38      1
2.92      1
13.20     1
8.25      1
8.44      1
1.84      1
9.95      1
2.96      1
0.16      1
2.86      1
7.40      1
3.99      1
9.00      1
2.44      1
6.25      1
3.87      1
6.02      1
7.90      1
3.23      1
2.54      1
2.69      1
3.98      1
4.02      1
1.97      1
7.80      1
15.00     1
0.61      1
1.53      1
4.16      1
7.52      1
0.19      1
0.57      1
3.72      1
4.52      1
2.62      1
4.21      1
9.14      1
2.82      1
4.94      1
4.95      1
5.31      1
3.19      1
2.97      1
4.40      1
4.63      1
2.98      1
4.79      1
4.78      1
6.16      1
7.56      1
6.44      1
5.30      1
2.72      1
1.11      1
2.63      1
2.21      1
2.48      1
3.83      1
10.75     1
8.35      1
2.37      1
7.15      1
4.67      1
1.74      1
9.30      1
5.15      1
4.86      1
3.39      1
5.40      1
3.63      1
2.61      1
2.77      1
2.34      1
3.79      1
5.49      1
0.17      1
6.30      1
10.00     1
5.75      1
6.10      1
2.11      1
1.06      1
11.25     1
3.78      1
Name: price, dtype: int64

In [24]:
df['price'].sort_values(ascending=False).head(10).index

Int64Index([2210, 2680, 2570, 1640, 429, 3016, 674, 1198, 1300, 1881], dtype='int64')

In [25]:
df[df.index.isin(df['price'].sort_values(ascending=False).head(10).index)]['society']

429     central park resorts
674            dlf the crest
1198           pioneer araya
1300         dlf the belaire
1640          m3m golfestate
1881           pioneer araya
2210    central park resorts
2570      ambience caitriona
2680      ambience caitriona
3016           dlf the crest
Name: society, dtype: object

In [26]:
df['price_per_sqft'].value_counts().head(5)

₹ 10,000/sq.ft.    19
₹ 8,000/sq.ft.     16
₹ 12,500/sq.ft.    16
₹ 6,666/sq.ft.     13
₹ 5,000/sq.ft.     13
Name: price_per_sqft, dtype: int64

In [27]:
df['price_per_sqft'] = df['price_per_sqft'].str.split("/").str.get(0).str.split(" ").str.get(1).str.replace(",","").str.strip().astype("float")

In [28]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [32]:
df['bedRoom'].value_counts()

3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: bedRoom, dtype: int64

In [40]:
df = df[~df['bedRoom'].isnull()]

In [50]:
df['bedRoom'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2997 entries, 0 to 3016
Series name: bedRoom
Non-Null Count  Dtype
--------------  -----
2997 non-null   int32
dtypes: int32(1)
memory usage: 35.1 KB

In [49]:
df['bedRoom'] = df['bedRoom'].str.split(" ").str.get(0).str.strip().astype("int")

In [52]:
df['bedRoom'].value_counts()

3    1437
2     944
4     478
1     104
5      31
6       3
Name: bedRoom, dtype: int64

In [55]:
df['bathroom'].value_counts()

2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: bathroom, dtype: int64

In [64]:
df['bathroom'].info()

<class 'pandas.core.series.Series'>
Int64Index: 2997 entries, 0 to 3016
Series name: bathroom
Non-Null Count  Dtype
--------------  -----
2997 non-null   int32
dtypes: int32(1)
memory usage: 35.1 KB

In [63]:
df['bathroom'] = df['bathroom'].str.split(" ").str.get(0).str.strip().astype("int")

In [65]:
df['bathroom'].value_counts()

2    1044
3     989
4     636
5     169
1     112
6      42
7       5
Name: bathroom, dtype: int64